In [51]:
import pandas as pd
from src import paths

In [68]:
raw_df = pd.read_csv(paths.data_interim_dir("dataset_ndvi.csv"), index_col=["ID", "IDpix"])

In [69]:
raw_df

                 lat        lon change_type last_non_change_date  \
ID  IDpix
79  2167  -33.228548 -71.653355      stable           17/07/2022
77  1964  -33.239866 -71.649043      stable           17/07/2022
    1992  -33.239597 -71.650121      stable           17/07/2022
64  1688  -34.048081 -71.803464      stable           22/02/2021
12  377   -33.436867 -71.266361      stable           02/02/2021
...              ...        ...         ...                  ...
420 8095  -35.162980 -71.939828        fire           02/08/2022
371 956   -34.569014 -71.547174        fire           02/08/2022
416 7223  -34.894563 -71.936863        fire           02/08/2022
418 7613  -34.235379 -71.769238        fire           14/05/2016
414 6412  -34.433188 -71.777323        fire           14/05/2016

          change_start_date change_ending_date vegetation_type  2000-01-03  \
ID  IDpix
79  2167         12/01/2006         17/07/2022          exotic         NaN
77  1964         12/01/2006         17/07/2022          exotic         NaN
    1992         12/01/2006         17/07/2022          exotic         NaN
64  1688         16/11/2004         22/02/2021           mixed    0.473691
12  377          30/12/2004         02/02/2021          native    0.633666
...                     ...                ...             ...         ...
420 8095         10/06/2005         02/08/2022          exotic         NaN
371 956          22/03/2018         01/08/2021          native         NaN
416 7223         02/01/2004         02/08/2022          exotic         NaN
418 7613         30/11/2018         07/10/2020          exotic         NaN
414 6412         07/10/2020         25/05/2021          exotic         NaN

           2000-01-11  2000-01-18  ...  2006-07-13  2007-06-14  2011-04-14  \
ID  IDpix                          ...
79  2167     0.486746    0.506629  ...         NaN         NaN         NaN
77  1964     0.399446    0.390229  ...         NaN         NaN         NaN
    1992     0.412398    0.398119  ...         NaN         NaN         NaN
64  1688     0.594318         NaN  ...         NaN         NaN         NaN
12  377      0.716169         NaN  ...         NaN         NaN         NaN
...               ...         ...  ...         ...         ...         ...
420 8095     0.389080    0.395282  ...         NaN         NaN         NaN
371 956      0.579955         NaN  ...         NaN         NaN         NaN
416 7223     0.803397    0.789779  ...         NaN         NaN         NaN
418 7613     0.704624    0.596280  ...         NaN         NaN         NaN
414 6412     0.280405    0.309308  ...         NaN         NaN         NaN

           2011-08-12  2012-10-26  2013-06-22  2014-09-13  2014-10-15  \
ID  IDpix
79  2167          NaN         NaN         NaN         NaN         NaN
77  1964          NaN         NaN         NaN         NaN         NaN
    1992          NaN         NaN         NaN         NaN         NaN
64  1688          NaN         NaN         NaN         NaN         NaN
12  377           NaN         NaN         NaN         NaN         NaN
...               ...         ...         ...         ...         ...
420 8095          NaN    0.829997         NaN         NaN         NaN
371 956           NaN         NaN         NaN         NaN         NaN
416 7223          NaN         NaN         NaN         NaN         NaN
418 7613          NaN         NaN         NaN         NaN         NaN
414 6412          NaN         NaN         NaN         NaN         NaN

           2016-05-13  2021-08-23
ID  IDpix
79  2167          NaN         NaN
77  1964          NaN         NaN
    1992          NaN         NaN
64  1688          NaN         NaN
12  377           NaN         NaN
...               ...         ...
420 8095          NaN         NaN
371 956           NaN         NaN
416 7223          NaN         NaN
418 7613          NaN         NaN
414 6412          NaN         NaN

[200 rows x 2545 columns]

In [52]:
test_df = pd.read_csv(paths.data_processed_dir("test_signal_filtered_dataset_ndvi.csv"), index_col=["ID", "IDpix"])
test_df.columns = pd.to_datetime(test_df.columns ) 
metadata_df = pd.read_csv(paths.data_processed_dir("metadata_filtered_dataset_ndvi.csv"), index_col=["ID", "IDpix"])

In [53]:
test_metadata = metadata_df.loc[test_df.index]
positive_cases_metadata = test_metadata[test_metadata["label"] == 1]

In [71]:
positive_cases_metadata[["last_non_change_date", "change_start_date", "change_ending_date", "change_type"]]

          last_non_change_date change_start_date change_ending_date  \
ID  IDpix
138 2250            2014-09-11        2016-02-23         2016-02-23
    2230            2014-09-11        2016-02-23         2016-02-23
89  555             2020-10-06        2020-12-02         2022-04-24
128 1450            2019-09-02        2019-12-19         2019-12-19
    1441            2019-09-02        2019-12-19         2019-12-19
99  878             2018-11-28        2020-03-09         2020-03-09
139 2262            2021-05-04        2021-10-22         2021-10-22
97  836             2018-11-28        2020-03-09         2020-03-09
91  716             2019-12-19        2020-10-06         2021-01-02
97  827             2018-11-28        2020-03-09         2020-03-09
131 1778            2021-05-25        2021-11-14         2022-04-05
85  389             2004-07-03        2006-04-07         2006-09-16
131 1723            2021-05-25        2021-11-14         2022-04-05
118 1252            2013-05-06        2014-08-12         2016-02-22
389 3352            2019-03-14        2019-09-01         2020-11-04
372 1216            2016-05-14        2018-03-24         2020-10-01
375 1742            2015-01-03        2016-03-18         2017-10-18
383 2828            2017-01-03        2017-11-20         2017-11-20
389 3444            2019-03-14        2019-09-01         2020-11-04
379 2102            2016-12-04        2017-10-18         2020-02-16
370 282             2016-05-14        2018-04-13         2020-10-14
    307             2016-05-14        2018-04-13         2020-10-14
    65              2016-05-14        2018-04-13         2020-10-14
391 3875            2021-10-22        2022-04-05         2022-04-05
379 2085            2016-12-04        2017-10-18         2020-02-16
370 537             2016-05-14        2018-04-13         2020-10-14
378 2016            2016-07-26        2019-03-01         2022-10-12
391 3868            2021-10-22        2022-04-05         2022-04-05
398 4224            2019-02-01        2021-09-30         2021-09-30
399 4533            2016-03-18        2018-02-24         2018-02-24
372 1298            2016-05-14        2018-03-24         2020-10-01
375 1798            2015-01-03        2016-03-18         2017-10-18
398 4231            2019-02-01        2021-09-30         2021-09-30
370 290             2016-05-14        2018-04-13         2020-10-14
378 1914            2016-07-26        2019-03-01         2022-10-12
392 3916            2016-05-02        2017-12-02         2018-11-06
375 1732            2015-01-03        2016-03-18         2017-10-18
371 687             2022-08-02        2018-03-22         2021-08-01
393 4029            2022-10-21        2006-02-12         2022-10-21
370 14              2016-05-14        2018-04-13         2020-10-14
371 956             2022-08-02        2018-03-22         2021-08-01

          change_type
ID  IDpix
138 2250      logging
    2230      logging
89  555       logging
128 1450      logging
    1441      logging
99  878       logging
139 2262      logging
97  836       logging
91  716       logging
97  827       logging
131 1778      logging
85  389       logging
131 1723      logging
118 1252      logging
389 3352         fire
372 1216         fire
375 1742         fire
383 2828         fire
389 3444         fire
379 2102         fire
370 282          fire
    307          fire
    65           fire
391 3875         fire
379 2085         fire
370 537          fire
378 2016         fire
391 3868         fire
398 4224         fire
399 4533         fire
372 1298         fire
375 1798         fire
398 4231         fire
370 290          fire
378 1914         fire
392 3916         fire
375 1732         fire
371 687          fire
393 4029         fire
370 14           fire
371 956          fire